### ISSUE TITLE
Photos in POI detail

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#1]
Any authenticated user shoud be able to upload photos related to a place. Upload process should be as easy and fool-proof as possible (multi-file upload, progress-bar, client-side downscaling, drag and drop). Photos can optionally contain captions.

**Comment by flaiming** [comment]
I think that https://github.com/blueimp/jQuery-File-Upload would be good for this, it has all that's asked and more. Only thing needed would be to add captions to uploaded images.

**Comment by jsmesami** [comment]
Yes, this was in my periscope, along with [this django example](https://github.com/sigurdga/django-jquery-file-upload), but within [this branch](https://github.com/jsmesami/naovoce/tree/fruit_photos), I decided to take a "minimum viable product" approach and postpone HTML5 features when I have more time (unless somebody else does the bells and whistles).

**Comment by jsmesami** [comment]
Added some image-upload support in [198a75d](https://github.com/jsmesami/naovoce/tree/198a75df07eef63827b2596044cf9c1e9e4ce8a5). Leaving the issue open for future enhancements.
