### ISSUE TITLE
Geosearch widget is visually broken on Android browser

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#15]

**Comment by flaiming** [comment]
You mean magnifying glass image?
![screenshot_2016-04-20-16-38-05](https://cloud.githubusercontent.com/assets/1169782/14678600/aa199966-0716-11e6-9803-21798a20bc39.png)

**Comment by jsmesami** [comment]
Yes. This was reported by a user, I don't own any Android device to test. It's ok on Chrome Canary though.
