### ISSUE TITLE
User profile customization

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#2]
User should be able to upload her custom avatar (this is now only possible with Gravatar). New feature would be optional motto.

**Comment by flaiming** [comment]
Let's do it as separate page, linked from user detail page (/pickers/<id-username>/) with link as something like /accounts/profile/. As for avatar, should there be some limits to px size, file size or file type?

**Comment by jsmesami** [comment]
Agreed, let's link it from here:
![screenshot](https://cloud.githubusercontent.com/assets/1177566/14017419/8cb2f7dc-f1c7-11e5-938a-516ff4ce7d41.png)
We could downscale the image in-browser, if user tries to upload something huge, or just limit the file size to something reasonable. Uploading images of silly sizes would easily exhaust limited RAM on current hosting. Let's also limit allowed file types to JPEG&PNG (?).

**Comment by flaiming** [comment]
Ok, great. I would also allow GIF images, it shouldn't do any harm if file size will be limited reasonably.

And for clarification, motto should be just simple text field?

**Comment by jsmesami** [comment]
Cool.
Yes, motto would be simple html-escaped text field (also no markdown), possibly displayed here?
![screenshot2](https://cloud.githubusercontent.com/assets/1177566/14018084/064e0ff6-f1cc-11e5-8294-2ade4deb1ad5.png)

**Comment by flaiming** [comment]
That's good place.

I would also suggest that links with Account settings, My messages etc. should be always displayed when visiting some section in user profile. It's a bit confusing that for example after going to My messages you have to click to your nickname in header to go back to your profile to change some other stuff.

**Comment by jsmesami** [comment]
A agree that user detail link is a bit hidden in the header and users often do not know what's the browser's "back" button for. We could provide them with some sort of breadcrumbs or so, but let's be careful not to clutter the UI too much.

**Comment by flaiming** [comment]
I ment not to add another link to header, but keep user settings menu i all profile pages, like this:
![profile settings](https://cloud.githubusercontent.com/assets/1169782/14042015/56b1421a-f276-11e5-9fb6-4c5ae3b6b262.png)

**Comment by jsmesami** [comment]
Thank you very much, I think we can close this issue for now (resolved by #9).
