### ISSUE TITLE
The app is leaking

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#20]
On production server, the application is slowly but constantly consuming more and more memory.
Some links:
http://www.lshift.net/blog/2008/11/14/tracing-python-memory-leaks/
https://pythonhosted.org/Pympler/
https://pypi.python.org/pypi/mem_top
https://pythonhosted.org/Pympler/muppy.html

**Comment by flaiming** [comment]
How do you run it in production, with uWSGI and Nginx?

**Comment by jsmesami** [comment]
Currently it's Gunicorn behind Nginx. Before that, it was Apache+mod_wsgi, and it was leaking too.

**Comment by jsmesami** [comment]
It's 64-bit CentOS7 vith Python 3.5 btw, but I don't think it makes any difference either.

**Comment by flaiming** [comment]
It may be fixed by setting `max_requests` to Gunicorn configuration so workers are restarted from time to time - http://blog.gingerlime.com/2011/django-memory-leaks-part-i/ . I would set it to 50 for example.

**Comment by jsmesami** [comment]
Cute article:) Although I suspect some serious garbage-collecting problem (a typical Django app does not have 200M/process and growing), the `--max-requests=50` is a great workaround and works like a charm. I can even grow number of workers now:)

**Comment by flaiming** [comment]
I'm glad it helped :) I should check if it's set on my own projects.
