### ISSUE TITLE
Attributions OSM on the map?

### ISSUE THREAD

**Issue by nesnera** [jsmesami/naovoce#46]
Na ovoce je super projekt, [místy až dojemný](https://na-ovoce.cz/fruit/detail/29223/), a vím, že OSM propagujete všude v patičkách. Jen zrovna u mapy samotné ne a tam bych to očekával nejvíc. Žel, jak na potvoru mě nenapadá místo, kde by to měli pěkně citlivě vyřešené. Dle mého [třeba tohle](http://staremapy.georeferencer.cz/map/o8hWc6yFyNOut6RHXUqtwq/201411251814-kBaVae/georeference) razí zbytečně moc.

**Comment by jsmesami** [comment]
Děkujeme za přízeň a hlavně za mapy:)
Jen na vysvětlenou: atribuce jsem v jedné fázi odstranil, protože překážely buttonku pro přidávání a přemístil je do patiček. Bohužel u velké mapy právě patička z praktických důvodů není. Snad jsem to tedy vhodně napravil.
