### ISSUE TITLE
There are almost no tests

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#5]
Build maximum coverage.

**Comment by flaiming** [comment]
WOuld be good to connect this project to https://travis-ci.org for automatic test running and https://coveralls.io/ for test coverage. I tried to connect my test repo https://github.com/flaiming/community-portal to these services (see badges at the top of Readme) and it's quite easy :)

**Comment by jsmesami** [comment]
Nice, I will do that when there are some more tests:)
