### ISSUE TITLE
Consider other map provider/s

### ISSUE THREAD

**Issue by jsmesami** [jsmesami/naovoce#6]
There is currently no option for satellite view. Also, bare OSM does not currently provide hi-res/vector maps.

**Comment by flaiming** [comment]
Well, I personally would use mapy.cz because they are better looking than Google maps, are better localized, without limits and also have API and marker clustering. Downside is that there probably wouldn't be so much ready-to-use plugins available.

**Comment by jsmesami** [comment]
We depend on [Leaflet.js](http://leafletjs.com/) because of all the battle-proven plugins. Leaflet can have different map providers, but I'm not sure if Mapy.cz is among them :/
For tiles, I have been pointed to [Mapbox](https://www.mapbox.com/) and [this](http://osm2vectortiles.org/), but had no time yet to explore and evaluate those and other options.

**Comment by jsmesami** [comment]
We have been contacted by TopGis, a company that supplies maps to Seznam.cz. We are working on future cooperation.
Features: better tiles, orthophoto tiles, land register layer.
