### ISSUE TITLE
App source code

### ISSUE THREAD

**Issue by niccokunzmann** [jsmesami/naovoce#66]
I am developing an open-source app for Mundraub.org which is the same as na ovoce in Germany.
I would like to cooperate. I see that this service is open-source which I would like to have for all sharing platforms as it makes sharing much easier.
Where can I see the source code of the app? I might be willing to incorporate source code of my app and make a joint version.

**Comment by jsmesami** [comment]
Hi Nicco. The mobile app is being developed by a third-party: [Touch Art](https://twitter.com/touchartdev) and is currently closed source. Please contact them for possible cooperation.
