### ISSUE TITLE
 Attributions OSM on the map again

### ISSUE THREAD

**Issue by Jakuje** [jsmesami/naovoce#70]
As already discussed few years ago (#46), the map attribution on the map page is not what it is supposed to be per [1].

The previous arguments about not having a good place to have this attribution probably does not apply anymore since there is already Ersi/Leaflet line in the map.

[1] https://www.openstreetmap.org/copyright

**Comment by jsmesami** [comment]
Oh. I added the attribution shortly after @nesnera rightfully complained that it should be also in the map. But during major design overhaul that happend some time ago, the external coder ditched it again and I didn't notice. I am genuinely sorry about this and will put it right soon.
